### ISSUE TITLE
Week 3 Report

### ISSUE THREAD

**Issue by BartMassey** [world0/world0-api#1]
Are you abandoning the front end? Needs copyright and license information in the README. Daniel, I'm confused	why you aren't on the repo (unless you're Molly Shove).

**Comment by jackelking** [comment]
My job is mostly back end stuff. I had thought that Molly was going to add
things to the README, but I'll contact her about that. Apparently, I was
listed as a private member of the project, I've fixed it and should be
visible on the project page now.

**Comment by spectralsun** [comment]
License will go in the LICENSE file in root of the repo, as is the standard practice with open source projects. I recommend GPL3 if we want to ensure it remain open source.

**Comment by BartMassey** [comment]
@spectralsun Yeah, leaving the LICENSE file is fine, but also give some indication of the license in the README so folks don't have to dig it out of there.

**Comment by spectralsun** [comment]
@BartMassey sounds good. FWIW GitHub seems to have a feature now where it detects the LICENSE file and shows the license, hopefully making it easier for it to be spotted at a glance (screenshot from a different project):

![license](https://user-images.githubusercontent.com/2507359/28307730-b032b812-6b58-11e7-960a-0d908c03477c.png)
